{% set name = "openresty" %}
{% set version = "1.17.8.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://openresty.org/download/openresty-{{ version }}.tar.gz
  sha256: a203fdbbc516f2eccd57272cb693e28ceb249ca858094598c8cab9a9b58ec5e5

build:
  number: 0 
  skip: True  # [not unix or not x86]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - autoconf
    - automake
    - libtool
    - pkg-config
    - perl
  host:
    - openssl
    - pcre
    - zlib

about:
    home: http://openresty.org

extra:
    recipe-maintainers:
      - bkreider
