{% set name = "openresty" %}
{% set version = "1.19.9.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://openresty.org/download/openresty-{{ version }}.tar.gz
  sha256: 576ff4e546e3301ce474deef9345522b7ef3a9d172600c62057f182f3a68c1f6 

build:
  number: 0 
  skip: True  # [not unix or not x86]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - autoconf
    - automake
    - libtool
    - pkg-config
    - perl
  host:
    - openssl
    - pcre
    - zlib

about:
    home: http://openresty.org

extra:
    recipe-maintainers:
      - bkreider
