{% set name = "openresty" %}
{% set version = "1.19.3.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://openresty.org/download/openresty-{{ version }}.tar.gz
  sha256: ce40e764990fbbeb782e496eb63e214bf19b6f301a453d13f70c4f363d1e5bb9 

build:
  number: 0 
  skip: True  # [not unix or not x86]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - autoconf
    - automake
    - libtool
    - pkg-config
    - perl
  host:
    - openssl
    - pcre
    - zlib

about:
    home: http://openresty.org

extra:
    recipe-maintainers:
      - bkreider
