{% set name = "openresty" %}
{% set version = "1.19.9.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://openresty.org/download/openresty-{{ version }}.tar.gz
  sha256: 576ff4e546e3301ce474deef9345522b7ef3a9d172600c62057f182f3a68c1f6 

build:
  number: 1
  skip: True  # [not unix or not x86]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - autoconf
    - automake
    - libtool
    - pkg-config
    - perl
  host:
    - openssl {{ openssl }}
    - pcre 8.45
    - zlib {{ zlib }}
  run:
    - openssl 3.*
    - pcre
    - zlib

about:
    home: https://openresty.org/
    license: BSD-3-Clause
    license_family: BSD 
    license_file: COPYRIGHT
    summary: OpenResty is a dynamic web platform based on NGINX and LuaJIT.
    description: >
      OpenResty is a full-fledged web platform that integrates our enhanced version
      of the Nginx core, our enhanced version of LuaJIT, many carefully written Lua
      libraries, lots of high quality 3rd-party Nginx modules, and most of their external
      dependencies. It is designed to help developers easily build scalable web
      applications, web services, and dynamic web gateways.
    doc_url: https://github.com/openresty/openresty/blob/master/README.markdown 
    dev_url: https://github.com/openresty/openresty

extra:
    recipe-maintainers:
      - bkreider
