{% set name = "openresty" %}
{% set version = "1.15.8.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://openresty.org/download/openresty-{{ version }}.tar.gz

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - autoconf
    - automake
    - libtool
    - pkg-config
    - perl
  host:
    - make
    - autoconf
    - automake
    - libtool
    - pkg-config
    - perl
    - openssl
    - pcre
    - zlib

about:
    home: http://openresty.org

extra:
    recipe-maintainers:
      - bkreider
